### ISSUE TITLE
Supports for any types of file ?

### ISSUE THREAD

**Issue by AlBlanc** [KasemJaffer/receive_sharing_intent#13]
Hi and thank you for this wonderful library,

I must admit I did not put my hands into this code yet. I have just have a question before continuing. 

I would like to be able to receive torrent files (No joke, it is something really official). I am wondering why your library is supporting "only" pictures, text and URLs. Do you think it is just a matter of few hours to extend it for other filetypes or there is a limitation from iOS?

I could help if you tell me this is possible.

**Comment by KasemJaffer** [comment]
I'm planning on supporting videos next. I'm not sure if iOS supports sharing other file types. You are welcome to help though.

**Comment by d-silveira** [comment]
I'm so glad to hear that @KasemJaffer , I really need that also

**Comment by filipenanclarez** [comment]
Hi,

I'am searching for similar library to enable receive files with 'open' option. Can you extend your librare to this?

My intention is do my app capable to open epub files, to show them.

It's possible?

**Comment by remoteportal** [comment]
Yes, I'm trying to figure out how to receive audio files.  I'm hoping they are a "subset" of videos.

**Comment by bentomikael** [comment]
send pdf files is possible?

**Comment by juanjoserodrigolazaro** [comment]
any idea of how to make this?

**Comment by Kruschak** [comment]
I forked it for my company, because we needed to accept every file-type. Perhaps this could help you (The fork of teamnifty). But the changes i made are to big to fit to the original concept of KasemJaffer so i did not send a pull request.

**Comment by AlBlanc** [comment]
Awesome news! Direct link: https://github.com/teamnifty/receive_file_intent (for peoples following the thread)

**Comment by Kruschak** [comment]
There is currently no plan for a PR because it throws the concept of KasemJaffer away, where he sends the mimetype of the file into flutter. So you will loose some functionality he achieved.

I think it would be easier to publish it as a new plugin instead. But i'm currently planning neither of these two options.

And first of all should @KasemJaffer decide which way we should go with it.

If you really need only the functionality of sharing each filetype you can use the git-link as plugin repository, but you have to change ShareViewController and the accepted files for android and ios.

**Comment by KasemJaffer** [comment]
@Kruschak Thanks for the fork to work on this issue. I look into what you have implemented and try adding it into my plugin.

**Comment by realcr** [comment]
@KasemJaffer : I am also very much interested in being able to process any file type.
@Kruschak : Thanks for your contribution, highly appreciated! Are you changes expected to work on ios too?

**Comment by KasemJaffer** [comment]
Version 1.4.0 now supports any types of file
