### ISSUE TITLE
iOS - Clicking on the share for ANY type doesn't get passed into flutter at all. 

### ISSUE THREAD

**Issue by kr1tzy** [KasemJaffer/receive_sharing_intent#36]
Setup is exactly what has been instructed. Tried it on multiple iOS versions, multiple phones, and altered the .plist in several ways with no luck.

**Comment by PabloCrucitta** [comment]
It happens the same to me.

**Comment by wrbl606** [comment]
Hey,
I found a solution. There's a missing piece in the example's README.

Since the Share Extension uses an `SharePhotos://` protocol to open the target app you need to specify matching **URL Type** in the Target Runner _Info_ page:

![obraz](https://user-images.githubusercontent.com/15102395/75967902-ce8e6800-5ecc-11ea-8cde-47f313f61da9.png)

After doing that (and applying the changes from @kr1tzy https://github.com/kr1tzy/receive_sharing_intent/commit/963e75cf5396dd32f3673d6159ef88722bd35b75 [Thanks!]) sharing should work as intended. 
Though it would work from now on, you will probably want to make the protocol more unique for your application to make sure that the Share Extension always opens your app instead of another one, with the same generic `SharePhotos://` protocol.

To do so, edit the protocol name above to something as unique as possible, like _yourAppNamePhotoSharingProtocol_ then go to the `ShareViewController.swift` and edit all occurances of `SharePhotos://` with your new protocol name.

**Comment by KasemJaffer** [comment]
> Hey,
> I found a solution. There's a missing piece in the example's README.
> 
> Since the Share Extension uses an `SharePhotos://` protocol to open the target app you need to specify matching **URL Type** in the Target Runner _Info_ page:
> 
> ![obraz](https://user-images.githubusercontent.com/15102395/75967902-ce8e6800-5ecc-11ea-8cde-47f313f61da9.png)
> 
> After doing that (and applying the changes from @kr1tzy [kr1tzy@963e75c](https://github.com/kr1tzy/receive_sharing_intent/commit/963e75cf5396dd32f3673d6159ef88722bd35b75) [Thanks!]) sharing should work as intended.
> Though it would work from now on, you will probably want to make the protocol more unique for your application to make sure that the Share Extension always opens your app instead of another one, with the same generic `SharePhotos://` protocol.
> 
> To do so, edit the protocol name above to something as unique as possible, like _yourAppNamePhotoSharingProtocol_ then go to the `ShareViewController.swift` and edit all occurances of `SharePhotos://` with your new protocol name.

@wrbl606 Thanks for the clarification...By the way adding the URL type is/was already mentioned in the README file. 

`receive_sharing_intent/example/README.md`

### iOS

#### 1. Add the following
ios/Runner/info.plist
```xml
...
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>SharePhotos</string>
			</array>
		</dict>
		<dict/>
	</array>
...
```

**Comment by mountaineer59** [comment]
does this not work correctly on an ios simulator...I have followed every solution. still no luck. I can only test on a simulator not on real iphone. (for some reason).
By the way, i have done every step correctly in xcode (as far as i know) and spent 10 hours on this flutter package.
I got it working on android easily but ios part beat the hell out of me.
can anyone please confirm if the issue is with ios simulator or not?

**Comment by britannio** [comment]
> does this not work correctly on an ios simulator...I have followed every solution. still no luck. I can only test on a simulator not on real iphone. (for some reason).
> By the way, i have done every step correctly in xcode (as far as i know) and spent 10 hours on this flutter package.
> I got it working on android easily but ios part beat the hell out of me.
> can anyone please confirm if the issue is with ios simulator or not?

I'm using the simulator and it's working

**Comment by britannio** [comment]
Looks like I broke something and it's not working on the simulator any more.

**Comment by elvisun** [comment]
I'm having the same issue, the share button opens the app but the data doesn't get passed into flutter at all for any types. Tried on real device and simulator, both aren't working.

Did anyone get this to work?

**Comment by marcqtan** [comment]
you need to add the app group capability for both target. (Runner and Share Extension) then it will work.
